version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=bank
    networks:
      - postgres-db-network

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://admin:admin@postgres:5432/bank?sslmode=disable
    depends_on:
      - postgres
    networks:
      - postgres-db-network


networks:
  postgres-db-network:
    driver: bridge
